version: "3"

services:
  chatbot:
    container_name: chatbot
    env_file: .env
    environment:
      - PORT=${PORT:-9090}
    image: catcatio/chatbot
    ports:
      - "${PORT:-9090}:${PORT:-9090}"
    volumes:
      - ./tmp:/go/src/app/tmp
      - ./main.go:/go/src/app/main.go
    working_dir: /go/src/app
    # Use this for first init
    command: bash -c "cd /go/src/app && glide init --non-interactive && glide update && fresh -c runner.conf main.go"
    # Use this forfaster speed after init
    # command: bash -c "fresh -c runner.conf main.go"
