version: "3"

services:
  chatbot:
    container_name: chatbot
    env_file: .env
    environment:
      - PORT=${PORT:-9090}
    image: catcatio/chatbot
    ports:
      - "${PORT:-9090}:${PORT:-9090}"
    volumes:
      - ./:/go/src/app
    working_dir: /go/src/app
    command: bash -c "cd /go/src/app && glide init --non-interactive && glide update && fresh -c runner.conf main.go"
